In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
import matplotlib.pyplot as plt

In [8]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [9]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [10]:
dates = pd.date_range('20130101', periods=6)

In [11]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [12]:
print(np.random.randn(6,4))

[[-1.23499199  0.93890484  1.03372801 -1.63199629]
 [ 0.63477335 -0.20770836 -0.17041671 -0.0219098 ]
 [ 0.33287077  0.37258204 -0.87859753  1.47350461]
 [ 0.10246495 -1.3562004   1.28168329  0.61232482]
 [-1.09181677  0.15252734  1.05733322  1.48376801]
 [-0.79753147  0.26820188  1.35028496  2.01902279]]


In [14]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))

In [15]:
df

A         B         C         D
2013-01-01 -1.299629  1.649019 -0.466075 -0.241054
2013-01-02  0.615450  1.507372 -0.313095  0.400830
2013-01-03  0.188199 -1.582604 -1.008718 -0.444454
2013-01-04  1.403156 -0.576316  0.020260 -0.960420
2013-01-05  1.083440 -0.218142 -0.383939  0.445124
2013-01-06 -0.302428  0.715559  1.420895 -0.242462

In [16]:
df2 = pd.DataFrame({
    'A' : 1.,
    'B' : pd.Timestamp('20130102'),
    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
    'D': np.array([3] * 4, dtype='int32'),
    'E':pd.Categorical(['test', 'train', 'test', 'train']),
    'F':'foo'
})

In [17]:
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [18]:
df.head()

A         B         C         D
2013-01-01 -1.299629  1.649019 -0.466075 -0.241054
2013-01-02  0.615450  1.507372 -0.313095  0.400830
2013-01-03  0.188199 -1.582604 -1.008718 -0.444454
2013-01-04  1.403156 -0.576316  0.020260 -0.960420
2013-01-05  1.083440 -0.218142 -0.383939  0.445124

In [19]:
df.tail(3)

A         B         C         D
2013-01-04  1.403156 -0.576316  0.020260 -0.960420
2013-01-05  1.083440 -0.218142 -0.383939  0.445124
2013-01-06 -0.302428  0.715559  1.420895 -0.242462

In [20]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [22]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [23]:
df.values

array([[-1.29962873,  1.64901861, -0.46607522, -0.24105428],
       [ 0.61545032,  1.50737235, -0.3130947 ,  0.40082981],
       [ 0.18819864, -1.58260361, -1.0087181 , -0.44445377],
       [ 1.40315588, -0.57631643,  0.02025999, -0.9604197 ],
       [ 1.08343966, -0.21814202, -0.38393856,  0.44512351],
       [-0.30242805,  0.71555884,  1.42089465, -0.242462  ]])

In [24]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.281365  0.249148 -0.121779 -0.173739
std    0.986143  1.266126  0.825899  0.531889
min   -1.299629 -1.582604 -1.008718 -0.960420
25%   -0.179771 -0.486773 -0.445541 -0.393956
50%    0.401824  0.248708 -0.348517 -0.241758
75%    0.966442  1.309419 -0.063079  0.240359
max    1.403156  1.649019  1.420895  0.445124

In [25]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -1.299629    0.615450    0.188199    1.403156    1.083440   -0.302428
B    1.649019    1.507372   -1.582604   -0.576316   -0.218142    0.715559
C   -0.466075   -0.313095   -1.008718    0.020260   -0.383939    1.420895
D   -0.241054    0.400830   -0.444454   -0.960420    0.445124   -0.242462

In [26]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01 -0.241054 -0.466075  1.649019 -1.299629
2013-01-02  0.400830 -0.313095  1.507372  0.615450
2013-01-03 -0.444454 -1.008718 -1.582604  0.188199
2013-01-04 -0.960420  0.020260 -0.576316  1.403156
2013-01-05  0.445124 -0.383939 -0.218142  1.083440
2013-01-06 -0.242462  1.420895  0.715559 -0.302428

In [27]:
df.sort_values(by='B')

A         B         C         D
2013-01-03  0.188199 -1.582604 -1.008718 -0.444454
2013-01-04  1.403156 -0.576316  0.020260 -0.960420
2013-01-05  1.083440 -0.218142 -0.383939  0.445124
2013-01-06 -0.302428  0.715559  1.420895 -0.242462
2013-01-02  0.615450  1.507372 -0.313095  0.400830
2013-01-01 -1.299629  1.649019 -0.466075 -0.241054

In [28]:
df['A']

2013-01-01   -1.299629
2013-01-02    0.615450
2013-01-03    0.188199
2013-01-04    1.403156
2013-01-05    1.083440
2013-01-06   -0.302428
Freq: D, Name: A, dtype: float64

In [29]:
df[0:3]

A         B         C         D
2013-01-01 -1.299629  1.649019 -0.466075 -0.241054
2013-01-02  0.615450  1.507372 -0.313095  0.400830
2013-01-03  0.188199 -1.582604 -1.008718 -0.444454